language: python

python:
    - "3.6"

services: mongodb

sudo: false

env:
    - TOX_ENV=dj111-py36-me016
    - TOX_ENV=dj111-py36-me018
    - TOX_ENV=dj22-py36-me016
    - TOX_ENV=dj22-py36-me018

matrix:
    fast_finish: true

install:
    - pip install tox virtualenv djangorestframework codecov

script:
    - tox -e $TOX_ENV

after_success:
    - codecov -e TOX_ENV

notifications:
    email: false
